AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# # 37signals house style
# inherit_gem:
#   rubocop-37signals: rubocop-ruby.yml
